version: '3.9'

services:
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    container_name: 'habitdb'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 11111111
      POSTGRES_DB: tracking_habit
      PGDATE: =/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"